TinyTapeout/tinytapeout_www

content/digital_design/wokwi_automated_testing/_index.en.md, content/digital_design/wokwi_lut_generator/_index.en.md
Rather than just suck in my README, I wrote this from scratch to try and keep with the tone and intended audience.  Used pre to keep the system from prettifying the tables: I wanted to be explicit and for cut&paste to be easy. Let me know if anything needs clarifying.
=> Wokwi truthtable automated testing documentation

content/hdl/testing/_index.md
do we need the same modification in the localized docs?
=> content/hdl/testing: fix verilog snippet

content/_index.es.md, content/contact/_index.es.md, content/credits/_index.es.md, content/faq/_index.es.md, content/making_asics/_index.es.md, content/runs/_index.es.md
updates to small pages:
- *content/* index
- *contact/* index
- *credits/* index
- *making_asics/* index
- *runs/* index
FAQ is now up to date.
=> [ES] updates to spanish translation of several pages.

content/digital_design/design_7seg/_index.es.md, content/digital_design/design_padlock/_index.es.md, content/digital_design/design_uart/_index.es.md, content/digital_design/holidays/_index.es.md, content/digital_design/puzzle_adder/_index.es.md, content/digital_design/puzzle_edgedetect/_index.es.md, content/digital_design/puzzle_flipflop/_index.es.md, content/digital_design/puzzle_padlock_seq/_index.es.md, content/digital_design/wokwi_automated_testing/_index.es.md, content/digital_design/wokwi_lut_generator/_index.es.md
- **first commit:** several minor changes to spanish translation, updated pages with missing/changed information.
- **second commit:** added spanish translation of the [Simple automated testing using truth tables](https://tinytapeout.com/digital_design/wokwi_automated_testing/) page, which was previously untranslated.
=> updates to spanish translation of Digital Design Guide section.

content/hdl/fpga_vs_asic/_index.es.md, content/hdl/important/_index.es.md, content/hdl/templates/_index.es.md, content/hdl/testing/_index.es.md, content/runs/tt01/_index.es.md
- **first commit:** HDL section.
- **second commit:** single tt01 run page.
- **third commit:** overlooked an outdated link.
=> final corrections to existing spanish pages.

content/siliwiz/resistors/_index.es.md
(if needed, I could commit more pages at once just so there aren't a billion PRs by the end of work. pages are fairly large though.)
=> [ES] siliwiz: spanish translation of 'draw a resistor' page.

content/siliwiz/parasitics/_index.es.md
=> [ES] siliwiz: spanish translation of parasitics page

content/siliwiz/divider/_index.es.md
small note: i checked the [PEX page](https://www.zerotoasiccourse.com/terminology/pex/) from the zero to hero course, and i found a very small typo in the first line, it says "Parastic" instead of "Parasitic". thought i'd bring it up here since it's quicker. 📝
=> [siliwiz] spanish translation of 'voltage divider' page.

content/siliwiz/capacitors/_index.es.md
finger slipped and i pressed enter before i finished writing the title for this PR
=> [ES] siliwiz: 'draw capacitor' translation

content/siliwiz/nmos/_index.es.md
second commit is making very small revisions to writing, and fixed broken link.
=> [ES] siliwiz: spanish translation of 'draw an nmosfet' page

content/siliwiz/inverter/_index.es.md
for some reason i always find a mistake right after making a commit even though i double check beforehand.
=> [ES] siliwiz: spanish translation of 'making a logic inverter' page.

content/siliwiz/cmosinverter/_index.es.md
with that, the entire siliwiz (how do semiconductors work) section is now available in spanish.
=> [ES] siliwiz: spanish translation of cmos page.

content/_index.ua.md, content/contact/_index.md, content/contact/_index.ua.md, content/credits/_index.ua.md
A few test page of the Ukrainian translation
=> index page translated

content/_index.es.md, content/press/_index.es.md, content/runs/_index.es.md
"press" page translation, and keeping spanish pages up to date with english pages.
=> [ES] missing spanish page translation + updates

content/_index.es.md, content/faq/_index.es.md, content/hdl/templates/_index.es.md, content/hdl/testing/_index.es.md, content/hdl/testing/_index.md, content/runs/_index.es.md
=> [ES] spanish updates.

content/specs/memory/_index.es.md, content/specs/pcb-tt123/_index.es.md, content/specs/pcb/_index.es.md
ignore the memory commit, i screwed up there by not switching to main before creating the new branch but it's the same thing.
=> [pcb] separated tt123 from tt4+ and updated.

content/specs/memory/_index.es.md
also i had completely forgotten i knew i could do multiple PRs at once by using multiple branches.
=> [memory] added spanish translation.

content/specs/gpio/_index.es.md, content/specs/gpio/_index.md
=> [gpio] added spanish translation. fixed small typos.

content/specs/analog/_index.es.md, content/specs/analog/_index.md
>line 100: "draw the rest of the owl"
is that a [reference](https://www.danielzarick.com/uploads/2018-05-draw-the-owl.jpg)??
=> [analog] added spanish translation. fixed small typos.

.gitignore, config.toml, content/_index.it.md
First pull request for the Italian version of tinytapeout.com.
=> Added Italian translation of homepage

content/specs/pinouts/_index.md
Just noticed this was broken by #80 - sorry!
=> Fix line breaks on QSPI pinout

content/digital_design/design_7seg/_index.en.md, content/digital_design/design_7seg/_index.es.md, content/digital_design/design_7seg/_index.ua.md, content/digital_design/design_padlock/_index.en.md, content/digital_design/design_padlock/_index.es.md
Note the changed instructions for the padlock design and its missing Spanish translation.
=> fix(design): wokwi flipflops driven by combo logic

content/guides/local-hardening/_index.md
Note that the guide refers to the `tt08-factory-test` repo that doesn't exist yet. Please either create it or just fork [htfab/tt08-factory-test](https://github.com/htfab/tt08-factory-test) before merging.
=> feat(guides): add local hardening guide using openlane2

content/specs/pinouts/_index.md
Add a link to the store and rephrase the sentences a little.
=> Tiny VGA: add link to store

content/_index.en.md
Added Wright State logo and added Wright State University to list of "our customers"
=> Added Wright State to list of our customers

content/guides/workshop/simulate-a-gate/_index.md
Another typo from Supercon workshop
=> s/swithes/switches in simulate-a-gate
